apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-web
  labels:
    app: app-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-rs
  template:
    metadata:
      labels:
        app: app-rs
    spec:
      containers:
        - name: web
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

